/* Generated By:JJTree&JavaCC: Do not edit this line. CNFParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CNFParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int START = 5;
  /** RegularExpression Id. */
  int END = 6;
  /** RegularExpression Id. */
  int STRING = 7;
  /** RegularExpression Id. */
  int NonTerm = 8;
  /** RegularExpression Id. */
  int Term = 9;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\"START\"",
    "\"END\"",
    "\"STRING:\"",
    "<NonTerm>",
    "<Term>",
    "\":=\"",
    "\";\"",
  };

}
