/* Generated By:JavaCC: Do not edit this line. CNFParserTreeConstants.java Version 5.0 */
public interface CNFParserTreeConstants
{
  public int JJTEXPRESSION = 0;
  public int JJTSTRINGTOTEST = 1;
  public int JJTSTARTATRIBUTION = 2;
  public int JJTATRIBUTION = 3;


  public String[] jjtNodeName = {
    "Expression",
    "stringToTest",
    "StartAtribution",
    "Atribution",
  };
}
/* JavaCC - OriginalChecksum=cc5c22756d81949cbd785756b71e3f7b (do not edit this line) */
