/* Generated By:JavaCC: Do not edit this line. CNFParserTreeConstants.java Version 5.0 */
public interface CNFParserTreeConstants
{
  public int JJTEXPRESSION = 0;
  public int JJTSTRINGTOTEST = 1;
  public int JJTSTARTATRIBUTION = 2;
  public int JJTATRIBUTION = 3;


  public String[] jjtNodeName = {
    "Expression",
    "stringToTest",
    "StartAtribution",
    "Atribution",
  };
}
/* JavaCC - OriginalChecksum=e63e634782d19bdea6aa2a43df4736a2 (do not edit this line) */
