/* Generated By:JavaCC: Do not edit this line. CNFParserTreeConstants.java Version 5.0 */
public interface CNFParserTreeConstants
{
  public int JJTEXPRESSION = 0;
  public int JJTSTARTATRIBUTION = 1;
  public int JJTATRIBUTION = 2;


  public String[] jjtNodeName = {
    "Expression",
    "StartAtribution",
    "Atribution",
  };
}
/* JavaCC - OriginalChecksum=85a36a957c91f4125548c9283f15ffcb (do not edit this line) */
