/* Generated By:JavaCC: Do not edit this line. CNFParserTreeConstants.java Version 5.0 */
package parser;

public interface CNFParserTreeConstants
{
  public int JJTEXPRESSION = 0;
  public int JJTSTARTATRIBUTION = 1;
  public int JJTATRIBUTION = 2;


  public String[] jjtNodeName = {
    "Expression",
    "StartAtribution",
    "Atribution",
  };
}
/* JavaCC - OriginalChecksum=ecf2bfdd7ff600a2ed271e90872c1ccb (do not edit this line) */
