/* Generated By:JavaCC: Do not edit this line. CNFParserTreeConstants.java Version 5.0 */
public interface CNFParserTreeConstants
{
  public int JJTEXPRESSION = 0;
  public int JJTATRIBUTION = 1;


  public String[] jjtNodeName = {
    "Expression",
    "Atribution",
  };
}
/* JavaCC - OriginalChecksum=b1131c9a940e0b594a33d3adb9a22ddf (do not edit this line) */
