/* Generated By:JJTree&JavaCC: Do not edit this line. CNFParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CNFParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LF = 4;
  /** RegularExpression Id. */
  int AT = 5;
  /** RegularExpression Id. */
  int SYMBOL = 6;
  /** RegularExpression Id. */
  int NonTerm = 7;
  /** RegularExpression Id. */
  int Term = 8;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\":=\"",
    "<SYMBOL>",
    "<NonTerm>",
    "<Term>",
    "\";\"",
  };

}
