/* Generated By:JavaCC: Do not edit this line. CNFParserTreeConstants.java Version 5.0 */
package parser;

public interface CNFParserTreeConstants
{
  public int JJTEXPRESSION = 0;
  public int JJTSTARTATRIBUTION = 1;
  public int JJTATRIBUTION = 2;


  public String[] jjtNodeName = {
    "Expression",
    "StartAtribution",
    "Atribution",
  };
}
/* JavaCC - OriginalChecksum=d2174ef964799bf44c65b33e814acb18 (do not edit this line) */
