/* Generated By:JavaCC: Do not edit this line. CNFParserTreeConstants.java Version 5.0 */
package parser;

public interface CNFParserTreeConstants
{
  public int JJTEXPRESSION = 0;
  public int JJTSTRINGTOTEST = 1;
  public int JJTSTARTATRIBUTION = 2;
  public int JJTATRIBUTION = 3;


  public String[] jjtNodeName = {
    "Expression",
    "stringToTest",
    "StartAtribution",
    "Atribution",
  };
}
/* JavaCC - OriginalChecksum=25981493865372261160225e38868d05 (do not edit this line) */
